### ISSUE TITLE
.DTS file failing to normalize

### ISSUE THREAD

**Issue by go2tom42** [slhck/ffmpeg-normalize#105]
**Expected behavior**
To normalize a DTS file into a WAV file

**Actual behavior**

Errors out

**Command**
The exact command you were trying to run:

```
ffmpeg-normalize "H:\Video\The Princess Bride\The Princess Bride_t00.dts" --debug -v -pr
```

Any output you get when running the command with the `--debug` flag:

```
DEBUG: found executable in path: C:\Program Files\ImageMagick-7.0.8-Q16\ffmpeg
DEBUG: found executable in path: C:\Program Files\ImageMagick-7.0.8-Q16\ffmpeg
DEBUG: Running command: ['C:\\Program Files\\ImageMagick-7.0.8-Q16\\ffmpeg', '-filters']
DEBUG: Parsing streams of H:\Video\The Princess Bride\The Princess Bride_t00.dts
DEBUG: Running command: ['C:\\Program Files\\ImageMagick-7.0.8-Q16\\ffmpeg', '-i', 'H:\\Video\\The Princess Bride\\The Princess Bride_t00.dts', '-c', 'copy', '-t', '0', '-map', '0', '-f', 'null', 'NUL']
DEBUG: Stream parsing command output:
DEBUG: ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, dts, from 'H:\Video\The Princess Bride\The Princess Bride_t00.dts':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: dts (DTS-HD MA), 48000 Hz, 5.1(side), s32p (24 bit)
Output #0, null, to 'NUL':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Audio: dts (DTS-HD MA), 48000 Hz, 5.1(side), s32p (24 bit)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=N/A time=00:00:00.00 bitrate=N/A speed=N/A
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)

Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\ffmpeg-normalize.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\ffmpeg_normalize\__main__.py", line 404, in main
    ffmpeg_normalize.add_media_file(input_file, output_file)
  File "c:\python37\lib\site-packages\ffmpeg_normalize\_ffmpeg_normalize.py", line 162, in add_media_file
    mf = MediaFile(self, input_file, output_file)
  File "c:\python37\lib\site-packages\ffmpeg_normalize\_media_file.py", line 41, in __init__
    self.parse_streams()
  File "c:\python37\lib\site-packages\ffmpeg_normalize\_media_file.py", line 76, in parse_streams
    duration = DUR_REGEX.search(line).groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

**Environment (please complete the following information):**
- [Windows 10 1903] Your operating system
- [Python 3.7.3] Your Python version / distribution (`python --version`)
- [ffmpeg version 4.1.3] Your ffmpeg version (`ffmpeg -version`)

**EXTRA INFO**

I grabbed the command sent from ffmpeg-normalize to FFmpeg, The command runs without issue

```
ffmpeg -progress - -nostats -nostdin -y -i "H:\Video\The Princess Bride\The Princess Bride_t00.dts" -filter_complex [0:0]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=0.0:print_format=json -vn -sn -f null NUL
```

Mediainfo details for DTS file

```
General
Count                                    : 331
Count of stream of this kind             : 1
Kind of stream                           : General
Kind of stream                           : General
Stream identifier                        : 0
Inform                                   : DTS XLL (DTS-HD Master Audio): 2.64 GiB
Count of audio streams                   : 1
Audio_Format_List                        : DTS XLL
Audio_Format_WithHint_List               : DTS XLL
Audio codecs                             : DTS XLL
Complete name                            : H:\Video\The Princess Bride\The Princess Bride_t00.dts
Folder name                              : H:\Video\The Princess Bride
File name extension                      : The Princess Bride_t00.dts
File name                                : The Princess Bride_t00
File extension                           : dts
Format                                   : DTS
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Format/Url                               : https://en.wikipedia.org/wiki/DTS_(sound_system)
Format/Extensions usually used           : dts dtshd
Commercial name                          : DTS-HD Master Audio
Commercial name                          : DTS-HD Master Audio
Format_AdditionalFeatures                : XLL
File size                                : 2838734404
File size                                : 2.64 GiB
File size                                : 3 GiB
File size                                : 2.6 GiB
File size                                : 2.64 GiB
File size                                : 2.644 GiB
Overall bit rate mode                    : VBR
Overall bit rate mode                    : Variable
File creation date                       : UTC 2019-07-12 16:32:09.650
File creation date (local)               : 2019-07-12 12:32:09.650
File last modification date              : UTC 2019-07-12 16:35:39.799
File last modification date (local)      : 2019-07-12 12:35:39.799

Audio
Count                                    : 277
Count of stream of this kind             : 1
Kind of stream                           : Audio
Kind of stream                           : Audio
Stream identifier                        : 0
Inform                                   : 48.0 kHz, 24 bits, 6 channels, DTS XLL (DTS-HD Master Audio)
Format                                   : DTS
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Format/Url                               : https://en.wikipedia.org/wiki/DTS_(sound_system)
Commercial name                          : DTS-HD Master Audio
Commercial name                          : DTS-HD Master Audio
Mode                                     : 16
Format settings, Endianness              : Big
Format_AdditionalFeatures                : XLL
Bit rate mode                            : VBR
Bit rate mode                            : Variable
Channel(s)                               : 6
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Channel positions                        : 3/2/0.1
Channel layout                           : C L R Ls Rs LFE
Samples per frame                        : 512
Sampling rate                            : 48000
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24
Bit depth                                : 24 bits
Compression mode                         : Lossless
Compression mode                         : Lossless
```

I can give you a google drive link to the file but it is 2.8gb

**Comment by slhck** [comment]
Thanks for the report. I see what the issue is already: it says “Duration: N/A” in your input. The duration might not be needed. I'll check if this can be fixed easily.
