### ISSUE TITLE
invalid cross-device link

### ISSUE THREAD

**Issue by brymck1** [slhck/ffmpeg-normalize#112]
**Expected behavior**
Execute the script without error.

**Actual behavior**
Running the script produces an error:
ERROR: Error while running command ['/usr/bin/ffmpeg', '-y', '-nostdin', '-i', 'Peppa Pig - S02E01 - Bubbles SDTV.avi', '-filter_complex', '[0:1]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=0.0:measured_i=-23.03:measured_lra=4.3:measured_tp=-10.24:measured_thresh=-33.42:linear=true:print_format=json[norm1]', '-map_metadata', '0', '-map_metadata:s:a:0', '0:s:a:0', '-map_metadata:s:v:0', '0:s:v:0', '-map_chapters', '0', '-map', '0:0', '-c:v', 'copy', '-map', '[norm1]', '-c:a', 'aac', '-b:a', '192k', '-c:s', 'copy', '/tmp/b8785ty4.avi']!
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/b8785ty4.avi' -> 'Peppa Pig - S02E01 - Bubbles SDTV.avi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bryan/.local/bin/ffmpeg-normalize", line 11, in <module>
    sys.exit(main())
  File "/home/bryan/.local/lib/python3.6/site-packages/ffmpeg_normalize/__main__.py", line 406, in main
    ffmpeg_normalize.run_normalization()
  File "/home/bryan/.local/lib/python3.6/site-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 188, in run_normalization
    raise e
  File "/home/bryan/.local/lib/python3.6/site-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 181, in run_normalization
    media_file.run_normalization()
  File "/home/bryan/.local/lib/python3.6/site-packages/ffmpeg_normalize/_media_file.py", line 146, in run_normalization
    for _ in self._second_pass():
  File "/home/bryan/.local/lib/python3.6/site-packages/ffmpeg_normalize/_media_file.py", line 335, in _second_pass
    raise e
  File "/home/bryan/.local/lib/python3.6/site-packages/ffmpeg_normalize/_media_file.py", line 329, in _second_pass
    shutil.move(temp_file_name, self.output_file)
  File "/usr/lib/python3.6/shutil.py", line 564, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.6/shutil.py", line 264, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 205, in copystat
    follow_symlinks=follow)
PermissionError: [Errno 1] Operation not permitted

**Command**
The exact command you were trying to run:

```
ffmpeg-normalize Peppa\ Pig\ -\ S02E01\ -\ Bubbles\ SDTV.avi -o Peppa\ Pig\ -\ S02E01\ -\ Bubbles\ SDTV.avi -c:a aac -b:a 192k -f
```

Any output you get when running the command with the `--debug` flag:

```
bryan@pvr:/media/mediashare/testaudiofix$ ffmpeg-normalize Peppa\ Pig\ -\ S02E01\ -\ Bubbles\ SDTV.avi -o Peppa\ Pig\ -\ S02E01\ -\ Bubbles\ SDTV.avi -c:a aac -b:a 192k -f -debug
DEBUG: found executable in path: /usr/bin/ffmpeg
DEBUG: found executable in path: /usr/bin/ffmpeg
DEBUG: Running command: ['/usr/bin/ffmpeg', '-filters']
DEBUG: Parsing streams of Peppa Pig - S02E01 - Bubbles SDTV.avi
DEBUG: Running command: ['/usr/bin/ffmpeg', '-i', 'Peppa Pig - S02E01 - Bubbles SDTV.avi', '-c', 'copy', '-t', '0', '-map', '0', '-f', 'null', '/dev/null']
DEBUG: Stream parsing command output:
DEBUG: ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, avi, from 'Peppa Pig - S02E01 - Bubbles SDTV.avi':
  Metadata:
    encoder         : Lavf57.83.100
  Duration: 00:05:06.44, start: 0.000000, bitrate: 908 kb/s
    Stream #0:0: Video: mpeg4 (Simple Profile) (XVID / 0x44495658), yuv420p, 720x400 [SAR 1:1 DAR 9:5], 697 kb/s, 29.97 fps, 29.97 tbr, 29.97 tbn, 29.97 tbc
    Stream #0:1: Audio: aac (LC) ([255][0][0][0] / 0x00FF), 44100 Hz, stereo, fltp, 192 kb/s
Output #0, null, to '/dev/null':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: mpeg4 (Simple Profile) (XVID / 0x44495658), yuv420p, 720x400 [SAR 1:1 DAR 9:5], q=2-31, 697 kb/s, 29.97 fps, 29.97 tbr, 29.97 tbn, 29.97 tbc
    Stream #0:1: Audio: aac (LC) ([255][0][0][0] / 0x00FF), 44100 Hz, stereo, fltp, 192 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=    0 fps=0.0 q=-1.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

DEBUG: Found duration: 306.044 s
DEBUG: Found video stream at index 0
DEBUG: Found audio stream at index 1
INFO: Normalizing file Peppa Pig - S02E01 - Bubbles SDTV.avi (1 of 1)
DEBUG: Running normalization for Peppa Pig - S02E01 - Bubbles SDTV.avi
DEBUG: Parsing normalization info for Peppa Pig - S02E01 - Bubbles SDTV.avi
INFO: Running first pass loudnorm filter for stream 1
DEBUG: Running ffmpeg command: ['/usr/bin/ffmpeg', '-nostdin', '-y', '-i', 'Peppa Pig - S02E01 - Bubbles SDTV.avi', '-filter_complex', '[0:1]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=0.0:print_format=json', '-vn', '-sn', '-f', 'null', '/dev/null']
DEBUG: Loudnorm first pass command output:
DEBUG: ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100
Input #0, avi, from 'Peppa Pig - S02E01 - Bubbles SDTV.avi':
Metadata:
encoder         : Lavf57.83.100
Duration: 00:05:06.44, start: 0.000000, bitrate: 908 kb/s
Stream #0:0: Video: mpeg4 (Simple Profile) (XVID / 0x44495658), yuv420p, 720x400 [SAR 1:1 DAR 9:5], 697 kb/s, 29.97 fps, 29.97 tbr, 29.97 tbn, 29.97 tbc
Stream #0:1: Audio: aac (LC) ([255][0][0][0] / 0x00FF), 44100 Hz, stereo, fltp, 192 kb/s
Stream mapping:
Stream #0:1 (aac) -> loudnorm
loudnorm -> Stream #0:0 (pcm_s16le)
Output #0, null, to '/dev/null':
Metadata:
encoder         : Lavf57.83.100
Stream #0:0: Audio: pcm_s16le, 192000 Hz, stereo, s16, 6144 kb/s
Metadata:
encoder         : Lavc57.107.100 pcm_s16le
bitrate=N/A
total_size=N/A
out_time_ms=15200000
out_time=00:00:15.200000
dup_frames=0
drop_frames=0
speed=30.3x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=31600000
out_time=00:00:31.600000
dup_frames=0
drop_frames=0
speed=31.5x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=48000000
out_time=00:00:48.000000
dup_frames=0
drop_frames=0
speed=31.9x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=64100000
out_time=00:01:04.100000
dup_frames=0
drop_frames=0
speed=  32x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=80600000
out_time=00:01:20.600000
dup_frames=0
drop_frames=0
speed=32.2x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=97000000
out_time=00:01:37.000000
dup_frames=0
drop_frames=0
speed=32.3x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=113300000
out_time=00:01:53.300000
dup_frames=0
drop_frames=0
speed=32.3x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=129800000
out_time=00:02:09.800000
dup_frames=0
drop_frames=0
speed=32.4x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=146300000
out_time=00:02:26.300000
dup_frames=0
drop_frames=0
speed=32.4x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=162900000
out_time=00:02:42.900000
dup_frames=0
drop_frames=0
speed=32.5x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=179300000
out_time=00:02:59.300000
dup_frames=0
drop_frames=0
speed=32.5x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=195600000
out_time=00:03:15.600000
dup_frames=0
drop_frames=0
speed=32.5x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=212000000
out_time=00:03:32.000000
dup_frames=0
drop_frames=0
speed=32.5x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=228600000
out_time=00:03:48.600000
dup_frames=0
drop_frames=0
speed=32.6x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=245000000
out_time=00:04:05.000000
dup_frames=0
drop_frames=0
speed=32.6x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=261300000
out_time=00:04:21.300000
dup_frames=0
drop_frames=0
speed=32.6x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=277500000
out_time=00:04:37.500000
dup_frames=0
drop_frames=0
speed=32.6x
progress=continue
bitrate=N/A
total_size=N/A
out_time_ms=294000000
out_time=00:04:54.000000
dup_frames=0
drop_frames=0
speed=32.6x
progress=continue
size=N/A time=00:05:06.31 bitrate=N/A speed=32.7x
bitrate=N/A
total_size=N/A
out_time_ms=306317646
out_time=00:05:06.317646
dup_frames=0
drop_frames=0
speed=32.7x
progress=end
video:0kB audio:229738kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Parsed_loudnorm_0 @ 0x55baeb095c60]
{
"input_i" : "-23.03",
"input_tp" : "-10.24",
"input_lra" : "4.30",
"input_thresh" : "-33.42",
"output_i" : "-22.79",
"output_tp" : "-9.85",
"output_lra" : "4.00",
"output_thresh" : "-33.16",
"normalization_type" : "dynamic",
"target_offset" : "-0.21"
}

DEBUG: Loudnorm stats parsed: {"input_i": "-23.03", "input_tp": "-10.24", "input_lra": "4.30", "input_thresh": "-33.42", "output_i": "-22.79", "output_tp": "-9.85", "output_lra": "4.00", "output_thresh": "-33.16", "normalization_type": "dynamic", "target_offset": "-0.21"}
INFO: Running second pass for Peppa Pig - S02E01 - Bubbles SDTV.avi
DEBUG: Running ffmpeg command: ['/usr/bin/ffmpeg', '-y', '-nostdin', '-i', 'Peppa Pig - S02E01 - Bubbles SDTV.avi', '-filter_complex', '[0:1]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=0.0:measured_i=-23.03:measured_lra=4.3:measured_tp=-10.24:measured_thresh=-33.42:linear=true:print_format=json[norm1]', '-map_metadata', '0', '-map_metadata:s:a:0', '0:s:a:0', '-map_metadata:s:v:0', '0:s:v:0', '-map_chapters', '0', '-map', '0:0', '-c:v', 'copy', '-map', '[norm1]', '-c:a', 'aac', '-b:a', '192k', '-c:s', 'copy', 'bug', '/tmp/6hvcy1rj.avi']
ERROR: Error while running command ['/usr/bin/ffmpeg', '-y', '-nostdin', '-i', 'Peppa Pig - S02E01 - Bubbles SDTV.avi', '-filter_complex', '[0:1]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=0.0:measured_i=-23.03:measured_lra=4.3:measured_tp=-10.24:measured_thresh=-33.42:linear=true:print_format=json[norm1]', '-map_metadata', '0', '-map_metadata:s:a:0', '0:s:a:0', '-map_metadata:s:v:0', '0:s:v:0', '-map_chapters', '0', '-map', '0:0', '-c:v', 'copy', '-map', '[norm1]', '-c:a', 'aac', '-b:a', '192k', '-c:s', 'copy', 'bug', '/tmp/6hvcy1rj.avi']!
Traceback (most recent call last):
  File "/home/bryan/.local/bin/ffmpeg-normalize", line 11, in <module>
    sys.exit(main())
  File "/home/bryan/.local/lib/python3.6/site-packages/ffmpeg_normalize/__main__.py", line 406, in main
    ffmpeg_normalize.run_normalization()
  File "/home/bryan/.local/lib/python3.6/site-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 188, in run_normalization
    raise e
  File "/home/bryan/.local/lib/python3.6/site-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 181, in run_normalization
    media_file.run_normalization()
  File "/home/bryan/.local/lib/python3.6/site-packages/ffmpeg_normalize/_media_file.py", line 146, in run_normalization
    for _ in self._second_pass():
  File "/home/bryan/.local/lib/python3.6/site-packages/ffmpeg_normalize/_media_file.py", line 335, in _second_pass
    raise e
  File "/home/bryan/.local/lib/python3.6/site-packages/ffmpeg_normalize/_media_file.py", line 321, in _second_pass
    for progress in cmd_runner.run_ffmpeg_command():
  File "/home/bryan/.local/lib/python3.6/site-packages/ffmpeg_normalize/_cmd_utils.py", line 89, in run_ffmpeg_command
    raise RuntimeError("Error running command {}: {}".format(self.cmd, str("\n".join(stderr))))
RuntimeError: Error running command ['/usr/bin/ffmpeg', '-y', '-nostdin', '-i', 'Peppa Pig - S02E01 - Bubbles SDTV.avi', '-filter_complex', '[0:1]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=0.0:measured_i=-23.03:measured_lra=4.3:measured_tp=-10.24:measured_thresh=-33.42:linear=true:print_format=json[norm1]', '-map_metadata', '0', '-map_metadata:s:a:0', '0:s:a:0', '-map_metadata:s:v:0', '0:s:v:0', '-map_chapters', '0', '-map', '0:0', '-c:v', 'copy', '-map', '[norm1]', '-c:a', 'aac', '-b:a', '192k', '-c:s', 'copy', 'bug', '/tmp/6hvcy1rj.avi']: ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100
Input #0, avi, from 'Peppa Pig - S02E01 - Bubbles SDTV.avi':
Metadata:
encoder         : Lavf57.83.100
Duration: 00:05:06.44, start: 0.000000, bitrate: 908 kb/s
Stream #0:0: Video: mpeg4 (Simple Profile) (XVID / 0x44495658), yuv420p, 720x400 [SAR 1:1 DAR 9:5], 697 kb/s, 29.97 fps, 29.97 tbr, 29.97 tbn, 29.97 tbc
Stream #0:1: Audio: aac (LC) ([255][0][0][0] / 0x00FF), 44100 Hz, stereo, fltp, 192 kb/s
[NULL @ 0x55ff80bb9320] Unable to find a suitable output format for 'bug'
bug: Invalid argument

```

**Environment (please complete the following information):**
- [Ubuntu 18.04] Your operating system
- [2.7.17 and 3.6.9 ] Your Python version / distribution (`python --version`)
- [3.4.6 ] Your ffmpeg version (`ffmpeg -version`)

If you do not fill out this information, your bug report may be closed.

**Comment by brymck1** [comment]
Looking to normalize audio across my video library (if you hadn't guessed from the file name, most of it is for my 3 year old :) ). 

/media/mediashare is mounted remotely from my NAS running freenas - the ffmpeg-normalize script is being run on my PVR server running ubuntu. I'm looking to eventually run the script as part of the file download process in nzbget (which runs on the PVR) to standardize all files as they are imported into my video library. Not sure if this is related to #39 as it's the same error message and seems to be related to an issue with writing across different file systems, or something else is going on.

**Comment by slhck** [comment]
I think it's the same issue, yes. What you can try is changing the temporary directory to the same folder as the one where the video is located:

```
TMPDIR=/media/mediashare ffmpeg-normalize input.avi -o output.avi -c:a aac -b:a 192k
```

That way, the temporary file should be written to `/media` (and thus the same device) and not to `/tmp`. Let me know if that works for you!

**Comment by brymck1** [comment]
That did not throw an error. Will look to incorporate that into nzbget, hopefully it works without issue. Thanks for the fast response!

**Comment by slhck** [comment]
Thanks for confirming!
