### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by rophin** [slhck/ffmpeg-normalize#155]
**:warning: Please read this carefully! If you do not fill out this information, your bug report may be closed.**

**Expected behavior**

We expected to become normalized in general.

**Actual behavior**
What happened?

If you do not rename the file to English, an error appears and the execution is stopped.

**Command**
The exact command you were trying to run:

```
ffmpeg-normalize 눈나연.mp4
```

Any output you get when running the command with the `--debug` flag:

```
DEBUG: found executable in path: C:\ProgramData\chocolatey\bin\ffmpeg
DEBUG: found executable in path: C:\ProgramData\chocolatey\bin\ffmpeg
DEBUG: Running command: ['C:\\ProgramData\\chocolatey\\bin\\ffmpeg', '-filters']
DEBUG: Parsing streams of 눈나연.mp4
DEBUG: Running command: ['C:\\ProgramData\\chocolatey\\bin\\ffmpeg', '-i', '눈나연.mp4', '-c', 'copy', '-t', '0', '-map', '0', '-f', 'null', 'NUL']
DEBUG: Stream parsing command output:
DEBUG: ffmpeg version 4.4-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '눈나연.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.76.100
  Duration: 00:08:18.36, start: 0.000000, bitrate: 1844 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 1706 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Output #0, null, to 'NUL':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.76.100
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 1706 kb/s, 60 fps, 60 tbr, 15360 tbn, 15360 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=    1 fps=0.0 q=-1.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
video:64kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

DEBUG: Found duration: 498.036 s
DEBUG: Found video stream at index 0
DEBUG: Found audio stream at index 1
INFO: Normalizing file 눈나연.mp4 (1 of 1)
DEBUG: Running normalization for 눈나연.mp4
DEBUG: Parsing normalization info for 눈나연.mp4
INFO: Running first pass loudnorm filter for stream 1
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\ffmpeg-normalize.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\ffmpeg_normalize\__main__.py", line 544, in main
    ffmpeg_normalize.run_normalization()
  File "c:\python39\lib\site-packages\ffmpeg_normalize\_ffmpeg_normalize.py", line 195, in run_normalization
    raise e
  File "c:\python39\lib\site-packages\ffmpeg_normalize\_ffmpeg_normalize.py", line 184, in run_normalization
    media_file.run_normalization()
  File "c:\python39\lib\site-packages\ffmpeg_normalize\_media_file.py", line 154, in run_normalization
    self._first_pass()
  File "c:\python39\lib\site-packages\ffmpeg_normalize\_media_file.py", line 183, in _first_pass
    for _ in fun():
  File "c:\python39\lib\site-packages\ffmpeg_normalize\_streams.py", line 214, in parse_loudnorm_stats
    for progress in cmd_runner.run_ffmpeg_command():
  File "c:\python39\lib\site-packages\ffmpeg_normalize\_cmd_utils.py", line 54, in run_ffmpeg_command
    for progress in ff.run_command_with_progress():
  File "c:\python39\lib\site-packages\ffmpeg_progress_yield\ffmpeg_progress_yield.py", line 91, in run_command_with_progress
    stderr_line = p.stdout.readline().strip()
UnicodeDecodeError: 'cp949' codec can't decode byte 0xeb in position 41: illegal multibyte sequence
```

**Environment (please complete the following information):**
- [ Windows 11 Pro 21H2 ]
- [ Python 3.9.6 ]
- [ ffmpeg version 4.4-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.2.0 (Rev6, Built by MSYS2 project) ]

**Comment by rophin** [comment]
I used a file that downloaded this [video](https://www.youtube.com/watch?v=Y3cz93gAXQk) with the youtube-dl command.

**Comment by slhck** [comment]
I cannot reproduce this under macOS, so it seems to be a problem specific to Windows.

Normally Python will handle all strings as UTF-8 and should not have a problem with any characters. The problem seems to be that the Windows console you are using is set to a different encoding, which cannot deal with the characters.

I pushed a possible fix in the latest version, can you please check if it works now?

**Comment by rophin** [comment]
> 
> 
> I cannot reproduce this under macOS, so it seems to be a problem specific to Windows.
> 
> Normally Python will handle all strings as UTF-8 and should not have a problem with any characters. The problem seems to be that the Windows console you are using is set to a different encoding, which cannot deal with the characters.
> 
> I pushed a possible fix in the latest version, can you please check if it works now?

```
C:\Users\rophini\Desktop\새 폴더>ffmpeg-normalize 눈나연.mp4
WARNING: The sample rate will automatically be set to 192 kHz by the loudnorm filter. Specify -ar/--sample-rate to override it.
```
It is working. Thank you.
