### ISSUE TITLE
Conversion failed on this video

### ISSUE THREAD

**Issue by mikemorr** [slhck/ffmpeg-normalize#161]
OS: Ubuntu 21.10 impish
Kernel: x86_64 Linux 5.13.0-22-lowlatency
Python 3.9.7
ffmpeg version 4.4-6ubuntu5
ffmpeg-normalize v1.22.4

Example video can be downloaded from here: 

https://drive.google.com/file/d/1woRLfvXfSxIhMaBxiNdHY9p1ncLVtbik/view

Command:
```
ffmpeg-normalize --debug VID_20170608_215913.mp4
```

Debug output:
```
DEBUG: found executable in path: /usr/bin/ffmpeg
DEBUG: found executable in path: /usr/bin/ffmpeg
DEBUG: Running command: ['/usr/bin/ffmpeg', '-filters']
DEBUG: Parsing streams of VID_20170608_215913.mp4
DEBUG: Running command: ['/usr/bin/ffmpeg', '-i', 'VID_20170608_215913.mp4', '-c', 'copy', '-t', '0', '-map', '0', '-f', 'null', '/dev/null']
DEBUG: Stream parsing command output:
DEBUG: ffmpeg version 4.4-6ubuntu5 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-7ubuntu1)
  configuration: --prefix=/usr --extra-version=6ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mpeg @ 0x55d923b30380] start time for stream 0 is not set in estimate_timings_from_pts
Input #0, mpeg, from 'VID_20170608_215913.mp4':
  Duration: 00:00:13.38, start: 0.528033, bitrate: 6327 kb/s
  Stream #0:0[0x1bf]: Data: dvd_nav_packet
  Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, progressive), 720x480 [SAR 1:1 DAR 3:2], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Side data:
      cpb: bitrate max/min/avg: 9000000/0/0 buffer size: 1835008 vbv_delay: N/A
  Stream #0:2[0x80]: Audio: ac3, 48000 Hz, mono, fltp, 448 kb/s
Output #0, null, to '/dev/null':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Data: dvd_nav_packet
  Stream #0:1: Video: mpeg2video (Main), yuv420p(tv, progressive), 720x480 [SAR 1:1 DAR 3:2], q=2-31, 29.97 fps, 29.97 tbr, 90k tbn, 90k tbc
    Side data:
      cpb: bitrate max/min/avg: 9000000/0/0 buffer size: 1835008 vbv_delay: N/A
  Stream #0:2: Audio: ac3, 48000 Hz, mono, fltp, 448 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
Press [q] to stop, [?] for help
frame=    1 fps=0.0 q=-1.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
video:31kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

DEBUG: Found duration: 13.038 s
DEBUG: Found video stream at index 1
DEBUG: Found audio stream at index 2
INFO: Normalizing file VID_20170608_215913.mp4 (1 of 1)
DEBUG: Running normalization for VID_20170608_215913.mp4
DEBUG: Parsing normalization info for VID_20170608_215913.mp4
INFO: Running first pass loudnorm filter for stream 2
DEBUG: Loudnorm first pass command output:
DEBUG: ffmpeg version 4.4-6ubuntu5 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 11 (Ubuntu 11.2.0-7ubuntu1)
configuration: --prefix=/usr --extra-version=6ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
[mpeg @ 0x56495ecfdc00] start time for stream 0 is not set in estimate_timings_from_pts
Input #0, mpeg, from 'VID_20170608_215913.mp4':
Duration: 00:00:13.38, start: 0.528033, bitrate: 6327 kb/s
Stream #0:0[0x1bf]: Data: dvd_nav_packet
Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, progressive), 720x480 [SAR 1:1 DAR 3:2], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
Side data:
cpb: bitrate max/min/avg: 9000000/0/0 buffer size: 1835008 vbv_delay: N/A
Stream #0:2[0x80]: Audio: ac3, 48000 Hz, mono, fltp, 448 kb/s
Stream mapping:
Stream #0:2 (ac3) -> loudnorm
loudnorm -> Stream #0:0 (pcm_s16le)
Output #0, null, to '/dev/null':
Metadata:
encoder         : Lavf58.76.100
Stream #0:0: Audio: pcm_s16le, 192000 Hz, mono, s16, 3072 kb/s
Metadata:
encoder         : Lavc58.134.100 pcm_s16le
bitrate=N/A
total_size=N/A
out_time_us=0
out_time_ms=0
out_time=00:00:00.000000
dup_frames=0
drop_frames=0
speed=   0x
progress=continue
size=N/A time=00:00:10.47 bitrate=N/A speed=  36x
bitrate=N/A
total_size=N/A
out_time_us=10476000
out_time_ms=10476000
out_time=00:00:10.476000
dup_frames=0
drop_frames=0
speed=  36x
progress=end
video:0kB audio:5016kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Parsed_loudnorm_0 @ 0x56495ee4d6c0]
{
"input_i" : "-13.62",
"input_tp" : "0.12",
"input_lra" : "5.60",
"input_thresh" : "-24.77",
"output_i" : "-21.29",
"output_tp" : "-4.52",
"output_lra" : "2.90",
"output_thresh" : "-32.15",
"normalization_type" : "dynamic",
"target_offset" : "-1.71"
}

DEBUG: Loudnorm stats parsed: {"input_i": "-13.62", "input_tp": "0.12", "input_lra": "5.60", "input_thresh": "-24.77", "output_i": "-21.29", "output_tp": "-4.52", "output_lra": "2.90", "output_thresh": "-32.15", "normalization_type": "dynamic", "target_offset": "-1.71"}
INFO: Running second pass for VID_20170608_215913.mp4
WARNING: The sample rate will automatically be set to 192 kHz by the loudnorm filter. Specify -ar/--sample-rate to override it.
ERROR: Error while running command /usr/bin/ffmpeg -y -nostdin -i VID_20170608_215913.mp4 -filter_complex '[0:2]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=-1.71:measured_i=-13.62:measured_lra=5.6:measured_tp=0.12:measured_thresh=-24.77:linear=true:print_format=json[norm2]' -map_metadata 0 -map_metadata:s:a:0 0:s:a:0 -map_metadata:s:v:0 0:s:v:0 -map_chapters 0 -map 0:1 -c:v copy -map '[norm2]' -c:a:0 pcm_s16le -c:s copy /tmp/7otxt9gd.mkv! Error: Error running command ['/usr/bin/ffmpeg', '-y', '-nostdin', '-i', 'VID_20170608_215913.mp4', '-filter_complex', '[0:2]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=-1.71:measured_i=-13.62:measured_lra=5.6:measured_tp=0.12:measured_thresh=-24.77:linear=true:print_format=json[norm2]', '-map_metadata', '0', '-map_metadata:s:a:0', '0:s:a:0', '-map_metadata:s:v:0', '0:s:v:0', '-map_chapters', '0', '-map', '0:1', '-c:v', 'copy', '-map', '[norm2]', '-c:a:0', 'pcm_s16le', '-c:s', 'copy', '/tmp/7otxt9gd.mkv']: ffmpeg version 4.4-6ubuntu5 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 11 (Ubuntu 11.2.0-7ubuntu1)
configuration: --prefix=/usr --extra-version=6ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
[mpeg @ 0x55ff3b40ac00] start time for stream 0 is not set in estimate_timings_from_pts
Input #0, mpeg, from 'VID_20170608_215913.mp4':
Duration: 00:00:13.38, start: 0.528033, bitrate: 6327 kb/s
Stream #0:0[0x1bf]: Data: dvd_nav_packet
Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, progressive), 720x480 [SAR 1:1 DAR 3:2], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
Side data:
cpb: bitrate max/min/avg: 9000000/0/0 buffer size: 1835008 vbv_delay: N/A
Stream #0:2[0x80]: Audio: ac3, 48000 Hz, mono, fltp, 448 kb/s
Stream mapping:
Stream #0:2 (ac3) -> loudnorm
Stream #0:1 -> #0:0 (copy)
loudnorm -> Stream #0:1 (pcm_s16le)
Output #0, matroska, to '/tmp/7otxt9gd.mkv':
Metadata:
encoder         : Lavf58.76.100
Stream #0:0: Video: mpeg2video (Main) (mpg2 / 0x3267706D), yuv420p(tv, progressive), 720x480 [SAR 1:1 DAR 3:2], q=2-31, 29.97 fps, 29.97 tbr, 1k tbn, 90k tbc
Side data:
cpb: bitrate max/min/avg: 9000000/0/0 buffer size: 1835008 vbv_delay: N/A
Stream #0:1: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, mono, s16, 768 kb/s
Metadata:
encoder         : Lavc58.134.100 pcm_s16le
frame=0
fps=0.00
stream_0_0_q=-1.0
bitrate=N/A
total_size=718
out_time_us=0
out_time_ms=0
out_time=00:00:00.000000
dup_frames=0
drop_frames=0
speed=   0x
progress=continue
[matroska @ 0x55ff3b5318c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 0x55ff3b5318c0] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
[matroska @ 0x55ff3b5318c0] Can't write packet with unknown timestamp
Error writing trailer of /tmp/7otxt9gd.mkv: Invalid argument
frame=   18 fps=0.0 q=-1.0 Lsize=     120kB time=00:00:00.54 bitrate=1813.0kbits/s speed= 110x
frame=18
fps=0.00
stream_0_0_q=-1.0
bitrate=1813.0kbits/s
total_size=122377
out_time_us=540000
out_time_ms=540000
out_time=00:00:00.540000
dup_frames=0
drop_frames=0
speed= 110x
progress=end
video:316kB audio:27kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Parsed_loudnorm_0 @ 0x55ff3b431cc0]
{
"input_i" : "-inf",
"input_tp" : "-29.38",
"input_lra" : "0.00",
"input_thresh" : "-70.00",
"output_i" : "-inf",
"output_tp" : "-38.76",
"output_lra" : "0.00",
"output_thresh" : "-70.00",
"normalization_type" : "linear",
"target_offset" : "inf"
}
Conversion failed!

Traceback (most recent call last):
  File "/home/user/.local/bin/ffmpeg-normalize", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.9/site-packages/ffmpeg_normalize/__main__.py", line 544, in main
    ffmpeg_normalize.run_normalization()
  File "/home/user/.local/lib/python3.9/site-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 195, in run_normalization
    raise e
  File "/home/user/.local/lib/python3.9/site-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 184, in run_normalization
    media_file.run_normalization()
  File "/home/user/.local/lib/python3.9/site-packages/ffmpeg_normalize/_media_file.py", line 162, in run_normalization
    for _ in self._second_pass():
  File "/home/user/.local/lib/python3.9/site-packages/ffmpeg_normalize/_media_file.py", line 369, in _second_pass
    raise e
  File "/home/user/.local/lib/python3.9/site-packages/ffmpeg_normalize/_media_file.py", line 358, in _second_pass
    raise e
  File "/home/user/.local/lib/python3.9/site-packages/ffmpeg_normalize/_media_file.py", line 350, in _second_pass
    for progress in cmd_runner.run_ffmpeg_command():
  File "/home/user/.local/lib/python3.9/site-packages/ffmpeg_normalize/_cmd_utils.py", line 54, in run_ffmpeg_command
    for progress in ff.run_command_with_progress():
  File "/home/user/.local/lib/python3.9/site-packages/ffmpeg_progress_yield/ffmpeg_progress_yield.py", line 107, in run_command_with_progress
    raise RuntimeError(
RuntimeError: Error running command ['/usr/bin/ffmpeg', '-y', '-nostdin', '-i', 'VID_20170608_215913.mp4', '-filter_complex', '[0:2]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=-1.71:measured_i=-13.62:measured_lra=5.6:measured_tp=0.12:measured_thresh=-24.77:linear=true:print_format=json[norm2]', '-map_metadata', '0', '-map_metadata:s:a:0', '0:s:a:0', '-map_metadata:s:v:0', '0:s:v:0', '-map_chapters', '0', '-map', '0:1', '-c:v', 'copy', '-map', '[norm2]', '-c:a:0', 'pcm_s16le', '-c:s', 'copy', '/tmp/7otxt9gd.mkv']: ffmpeg version 4.4-6ubuntu5 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 11 (Ubuntu 11.2.0-7ubuntu1)
configuration: --prefix=/usr --extra-version=6ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
[mpeg @ 0x55ff3b40ac00] start time for stream 0 is not set in estimate_timings_from_pts
Input #0, mpeg, from 'VID_20170608_215913.mp4':
Duration: 00:00:13.38, start: 0.528033, bitrate: 6327 kb/s
Stream #0:0[0x1bf]: Data: dvd_nav_packet
Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, progressive), 720x480 [SAR 1:1 DAR 3:2], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
Side data:
cpb: bitrate max/min/avg: 9000000/0/0 buffer size: 1835008 vbv_delay: N/A
Stream #0:2[0x80]: Audio: ac3, 48000 Hz, mono, fltp, 448 kb/s
Stream mapping:
Stream #0:2 (ac3) -> loudnorm
Stream #0:1 -> #0:0 (copy)
loudnorm -> Stream #0:1 (pcm_s16le)
Output #0, matroska, to '/tmp/7otxt9gd.mkv':
Metadata:
encoder         : Lavf58.76.100
Stream #0:0: Video: mpeg2video (Main) (mpg2 / 0x3267706D), yuv420p(tv, progressive), 720x480 [SAR 1:1 DAR 3:2], q=2-31, 29.97 fps, 29.97 tbr, 1k tbn, 90k tbc
Side data:
cpb: bitrate max/min/avg: 9000000/0/0 buffer size: 1835008 vbv_delay: N/A
Stream #0:1: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, mono, s16, 768 kb/s
Metadata:
encoder         : Lavc58.134.100 pcm_s16le
frame=0
fps=0.00
stream_0_0_q=-1.0
bitrate=N/A
total_size=718
out_time_us=0
out_time_ms=0
out_time=00:00:00.000000
dup_frames=0
drop_frames=0
speed=   0x
progress=continue
[matroska @ 0x55ff3b5318c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 0x55ff3b5318c0] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
[matroska @ 0x55ff3b5318c0] Can't write packet with unknown timestamp
Error writing trailer of /tmp/7otxt9gd.mkv: Invalid argument
frame=   18 fps=0.0 q=-1.0 Lsize=     120kB time=00:00:00.54 bitrate=1813.0kbits/s speed= 110x
frame=18
fps=0.00
stream_0_0_q=-1.0
bitrate=1813.0kbits/s
total_size=122377
out_time_us=540000
out_time_ms=540000
out_time=00:00:00.540000
dup_frames=0
drop_frames=0
speed= 110x
progress=end
video:316kB audio:27kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Parsed_loudnorm_0 @ 0x55ff3b431cc0]
{
"input_i" : "-inf",
"input_tp" : "-29.38",
"input_lra" : "0.00",
"input_thresh" : "-70.00",
"output_i" : "-inf",
"output_tp" : "-38.76",
"output_lra" : "0.00",
"output_thresh" : "-70.00",
"normalization_type" : "linear",
"target_offset" : "inf"
}
Conversion failed!
```

**Comment by slhck** [comment]
Thanks for the detailed report. This is an issue with the original file that does not have proper timestamps set. Using the following option makes the conversion work on my end:

```
ffmpeg-normalize --extra-input-options='-fflags +genpts' VID_20170608_215913.mp4
```
