### ISSUE TITLE
Option 'measure_overall' not found

### ISSUE THREAD

**Issue by adhadse** [slhck/ffmpeg-normalize#170]
**Expected behavior**
I was trying to run [YourTTS colab demo](https://colab.research.google.com/drive/1ftI0x16iqKgiQFgTjTDgRpOM1wC1U-yS?usp=sharing) and in that I was trying to normalize the given input `.wav` file for input that's when the error occurred.

I tried making sure FFmpeg was installed and is latest version:
```
!apt install ffmpeg
```
> ffmpeg is already the newest version (7:3.4.8-0ubuntu0.2)

**Actual behavior**
```
Input #0, wav, from '2824500218234776405_vocals.wav':
Metadata:
encoder         : Lavf58.45.100
Duration: 00:00:03.01, bitrate: 1411 kb/s
Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
[Parsed_astats_0 @ 0x5622cbf39540] Option 'measure_overall' not found
[AVFilterGraph @ 0x5622cbf02be0] Error initializing filter 'astats' with args 'measure_overall=Peak_level+RMS_level:measure_perchannel=0'
Error initializing complex filters.
Option not found
```

**Command**
The exact command you were trying to run:

```
for sample in reference_files:
    !ffmpeg-normalize $sample -nt rms -t=-27 -o $sample -ar 16000 -f
```

For 1 file:
```
!ffmpeg-normalize 11186372305865029514_vocals.wav -nt rms -t=-27 -o 11186372305865029514_vocals.wav -d -ar 16000 -f  
```

Any output you get when running the command with the `--debug` flag:

```
DEBUG: found executable in path: /usr/bin/ffmpeg
DEBUG: found executable in path: /usr/bin/ffmpeg
DEBUG: Running command: ['/usr/bin/ffmpeg', '-filters']
DEBUG: Parsing streams of 11186372305865029514_vocals.wav
DEBUG: Running command: ['/usr/bin/ffmpeg', '-i', '11186372305865029514_vocals.wav', '-c', 'copy', '-t', '0', '-map', '0', '-f', 'null', '/dev/null']
DEBUG: Stream parsing command output:
DEBUG: ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from '11186372305865029514_vocals.wav':
  Metadata:
    encoder         : Lavf58.45.100
  Duration: 00:00:03.87, bitrate: 1411 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
Output #0, null, to '/dev/null':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)

DEBUG: Found duration: 3.087 s
DEBUG: Found audio stream at index 0
INFO: Normalizing file 11186372305865029514_vocals.wav (1 of 1)
DEBUG: Running normalization for 11186372305865029514_vocals.wav
DEBUG: Parsing normalization info for 11186372305865029514_vocals.wav
INFO: Running first pass astats filter for stream 0
DEBUG: Running command: ['/usr/bin/ffmpeg', '-nostdin', '-y', '-i', '11186372305865029514_vocals.wav', '-filter_complex', '[0:0]astats=measure_overall=Peak_level+RMS_level:measure_perchannel=0', '-vn', '-sn', '-f', 'null', '/dev/null']
Traceback (most recent call last):
  File "/usr/local/bin/ffmpeg-normalize", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_normalize/__main__.py", line 544, in main
    ffmpeg_normalize.run_normalization()
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 195, in run_normalization
    raise e
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 184, in run_normalization
    media_file.run_normalization()
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_normalize/_media_file.py", line 154, in run_normalization
    self._first_pass()
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_normalize/_media_file.py", line 183, in _first_pass
    for _ in fun():
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_normalize/_streams.py", line 155, in parse_astats
    for progress in cmd_runner.run_ffmpeg_command():
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_normalize/_cmd_utils.py", line 55, in run_ffmpeg_command
    for progress in ff.run_command_with_progress():
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_progress_yield/ffmpeg_progress_yield.py", line 108, in run_command_with_progress
    "Error running command {}: {}".format(self.cmd, str("\n".join(stderr)))
RuntimeError: Error running command ['/usr/bin/ffmpeg', '-nostdin', '-y', '-i', '11186372305865029514_vocals.wav', '-filter_complex', '[0:0]astats=measure_overall=Peak_level+RMS_level:measure_perchannel=0', '-vn', '-sn', '-f', 'null', '/dev/null']: ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from '11186372305865029514_vocals.wav':
Metadata:
encoder         : Lavf58.45.100
Duration: 00:00:03.87, bitrate: 1411 kb/s
Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
[Parsed_astats_0 @ 0x55d536ca3540] Option 'measure_overall' not found
[AVFilterGraph @ 0x55d536c6cbe0] Error initializing filter 'astats' with args 'measure_overall=Peak_level+RMS_level:measure_perchannel=0'
Error initializing complex filters.
Option not found
```

**Environment (please complete the following information):**
- [X] Your operating system: **Linux OS-release: 5.4.144+ | Google Colab**
- [X] Your Python version / distribution (`python --version`): **Python 3.7.12**
- [X] Your ffmpeg version (`ffmpeg -version`) **3.4.8-0ubuntu0.2**

**Comment by slhck** [comment]
Please update to a recent version of ffmpeg. Yours is quite outdated. You can use the static build download from the FFmpeg website.

**Comment by adhadse** [comment]
Solved! Yes `FFmpeg` version was really old. Bad luck from Google Colab side. Added PPA and updating helped

```
!add-apt-repository ppa:savoury1/ffmpeg4
!apt-get update
!apt-get install ffmpeg
```

**Comment by slhck** [comment]
Glad you got it working!
