### ISSUE TITLE
EXTRA_OUTPUT_OPTIONS are not parsed correctly: `-vbr` is parsed like `-v br`

### ISSUE THREAD

**Issue by homocomputeris** [slhck/ffmpeg-normalize#228]
**:warning: Please read this carefully and edit the example responses! If you do not fill out this information, your bug report may be closed without comment.**

**Checklist** (please tick all boxes)
- [x] I am using the latest version of `ffmpeg-normalize` (run `pip3 install --upgrade ffmpeg-normalize`)
- [x] I am using the latest stable version of `ffmpeg` or a recent build from Git master

**Expected behavior**
Using
```
parallel ffmpeg-normalize {} -c:a libopus -b:a 48k -e '[ "-vbr", "on", "-application", "voip" ]' -o {.}.opus ::: *.mp3(N) *.ogg(N)
```
the `-e '[ "-vbr", "on", "application", "voip" ]'` is passed to ffmpeg

**Actual behavior**
ffmpeg-normalize thinks that `-vbr` is `-v br`

**Command**
The exact command you were trying to run:

```
parallel ffmpeg-normalize {} -c:a libopus -b:a 48k -e '[ "-vbr", "on", "-application", "voip" ]' -o {.}.opus ::: *.mp3(N) *.ogg(N)
```

Any output you get when running the command with the `--debug` flag:

```
usage: ffmpeg-normalize [-h] [-o OUTPUT [OUTPUT ...]] [-of OUTPUT_FOLDER] [-f]
                        [-d] [-v] [-q] [-n] [-pr] [--version]
                        [-nt {ebu,rms,peak}] [-t TARGET_LEVEL] [-p]
                        [-lrt LOUDNESS_RANGE_TARGET]
                        [--keep-loudness-range-target] [-tp TRUE_PEAK]
                        [--offset OFFSET] [--dual-mono] [--dynamic]
                        [-c:a AUDIO_CODEC] [-b:a AUDIO_BITRATE]
                        [-ar SAMPLE_RATE] [-koa] [-prf PRE_FILTER]
                        [-pof POST_FILTER] [-vn] [-c:v VIDEO_CODEC] [-sn]
                        [-mn] [-cn] [-ei EXTRA_INPUT_OPTIONS]
                        [-e EXTRA_OUTPUT_OPTIONS] [-ofmt OUTPUT_FORMAT]
                        [-ext EXTENSION]
                        input [input ...]
ffmpeg-normalize: error: argument -v/--verbose: ignored explicit argument 'br,'
```

**Environment (please complete the following information):**
- [x] Your operating system
> macOS Vertura 13.3.1 (22E262)
- [x] Your Python version / distribution (`python3 --version` or `python --version`)
> Python 3.11.3
- [x] Your ffmpeg version (`ffmpeg -version`)
```shell
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
configuration: --prefix=/usr/local/Cellar/ffmpeg/6.0 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```

**Comment by slhck** [comment]
Does it work when you don't use parallel?

**Comment by slhck** [comment]
The reason I'm asking is that parallel and quoting is a bit unintuitive at times. It appears like the single quote argument around the extra options gets split into invididual arguments. You may have more luck defining the ffmpeg normalize call as a shell function first, or putting it into a small script.

**Comment by homocomputeris** [comment]
I got this:
```shell
ffmpeg-normalize 13.mp3 -c:a libopus -b:a 48k -e '[ "-vbr", "on", "application", "voip" ]' -o 13.opus

ERROR: Error while running command /usr/local/bin/ffmpeg -hide_banner -y -i 13.mp3 -filter_complex '[0:0]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=-0.17:measured_i=-13.43:measured_lra=3.5:measured_tp=-0.01:measured_thresh=-24.41:linear=true:print_format=json[norm0]' -map_metadata 0 -map_metadata:s:a:0 0:s:a:0 -map_chapters 0 -map '[norm0]' -c:a libopus -b:a 48k -c:s copy -vbr on application voip /var/folders/9x/2rlqfmqn6_55c24c568s9clw0000gn/T/tmp7t2xf7yq/out.opus! Error: Error running command ['/usr/local/bin/ffmpeg', '-hide_banner', '-y', '-i', '13.mp3', '-filter_complex', '[0:0]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=-0.17:measured_i=-13.43:measured_lra=3.5:measured_tp=-0.01:measured_thresh=-24.41:linear=true:print_format=json[norm0]', '-map_metadata', '0', '-map_metadata:s:a:0', '0:s:a:0', '-map_chapters', '0', '-map', '[norm0]', '-c:a', 'libopus', '-b:a', '48k', '-c:s', 'copy', '-vbr', 'on', 'application', 'voip', '/var/folders/9x/2rlqfmqn6_55c24c568s9clw0000gn/T/tmp7t2xf7yq/out.opus']: [mp3 @ 0x7f7bff904440] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '13.mp3':
Metadata:
encoded_by      : iTunes v7.0
Duration: 00:01:31.25, start: 0.000000, bitrate: 192 kb/s
Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 192 kb/s
[NULL @ 0x7f7bff9126c0] Unable to find a suitable output format for 'application'
application: Invalid argument
Traceback (most recent call last):
  File "/Users/user/.local/bin/ffmpeg-normalize", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/user/.local/pipx/venvs/ffmpeg-normalize/lib/python3.11/site-packages/ffmpeg_normalize/__main__.py", line 553, in main
    ffmpeg_normalize.run_normalization()
  File "/Users/user/.local/pipx/venvs/ffmpeg-normalize/lib/python3.11/site-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 237, in run_normalization
    raise e
  File "/Users/user/.local/pipx/venvs/ffmpeg-normalize/lib/python3.11/site-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 227, in run_normalization
    media_file.run_normalization()
  File "/Users/user/.local/pipx/venvs/ffmpeg-normalize/lib/python3.11/site-packages/ffmpeg_normalize/_media_file.py", line 194, in run_normalization
    for _ in self._second_pass():
  File "/Users/user/.local/pipx/venvs/ffmpeg-normalize/lib/python3.11/site-packages/ffmpeg_normalize/_media_file.py", line 406, in _second_pass
    raise e
  File "/Users/user/.local/pipx/venvs/ffmpeg-normalize/lib/python3.11/site-packages/ffmpeg_normalize/_media_file.py", line 397, in _second_pass
    raise e
  File "/Users/user/.local/pipx/venvs/ffmpeg-normalize/lib/python3.11/site-packages/ffmpeg_normalize/_media_file.py", line 393, in _second_pass
    yield from CommandRunner().run_ffmpeg_command(cmd)
  File "/Users/user/.local/pipx/venvs/ffmpeg-normalize/lib/python3.11/site-packages/ffmpeg_normalize/_cmd_utils.py", line 80, in run_ffmpeg_command
    yield from ff.run_command_with_progress()
  File "/Users/user/.local/pipx/venvs/ffmpeg-normalize/lib/python3.11/site-packages/ffmpeg_progress_yield/ffmpeg_progress_yield.py", line 191, in run_command_with_progress
    raise RuntimeError(f"Error running command {self.cmd}: {_pretty_stderr}")
RuntimeError: Error running command ['/usr/local/bin/ffmpeg', '-hide_banner', '-y', '-i', '13.mp3', '-filter_complex', '[0:0]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=-0.17:measured_i=-13.43:measured_lra=3.5:measured_tp=-0.01:measured_thresh=-24.41:linear=true:print_format=json[norm0]', '-map_metadata', '0', '-map_metadata:s:a:0', '0:s:a:0', '-map_chapters', '0', '-map', '[norm0]', '-c:a', 'libopus', '-b:a', '48k', '-c:s', 'copy', '-vbr', 'on', 'application', 'voip', '/var/folders/9x/2rlqfmqn6_55c24c568s9clw0000gn/T/tmp7t2xf7yq/out.opus']: [mp3 @ 0x7f7bff904440] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '13.mp3':
Metadata:
encoded_by      : iTunes v7.0
Duration: 00:01:31.25, start: 0.000000, bitrate: 192 kb/s
Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 192 kb/s
[NULL @ 0x7f7bff9126c0] Unable to find a suitable output format for 'application'
application: Invalid argument
```

**Comment by homocomputeris** [comment]
Without parallel it works fine.

Also, I forgot to put `-` before `application`.

**Comment by homocomputeris** [comment]
> The reason I'm asking is that parallel and quoting is a bit unintuitive at times.

Yeah, I completely forgot about this. Thanks a lot!

**Comment by homocomputeris** [comment]
In this particular case, running `parallel -q` worked fine.
