### ISSUE TITLE
Error Invalid sample rate

### ISSUE THREAD

**Issue by Rouzax** [slhck/ffmpeg-normalize#62]
- [x] Your operating system
Windows 2016
- [x] Your Python version / distribution
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
- [x] Your ffmpeg version
ffmpeg version N-90173-gfa0c9d69d3
- [x] The exact command you were trying to run
`ffmpeg-normalize "De SprookjesBoom - S07E15 - De Grens.mkv" -c:a ac3 -b:a 160k --debug`
- [x] Any output you get when running the command with the `--debug` flag
```
C:\DATA\Private\temp\MakeMKV>ffmpeg-normalize "De SprookjesBoom - S07E15 - De Grens.mkv" -c:a ac3 -b:a 160k --debug
DEBUG: found executable in path: C:\Windows\system32\ffmpeg
DEBUG: found executable in path: C:\Windows\system32\ffmpeg
DEBUG: Running command: ['C:\\Windows\\system32\\ffmpeg', '-filters']
WARNING: Output directory 'normalized' does not exist, will create
DEBUG: Parsing streams of De SprookjesBoom - S07E15 - De Grens.mkv
DEBUG: Running command: ['C:\\Windows\\system32\\ffmpeg', '-i', 'De SprookjesBoom - S07E15 - De Grens.mkv', '-c', 'copy', '-t', '0', '-map', '0', '-f', 'null', 'NUL']
DEBUG: Stream parsing command output:
DEBUG: ffmpeg version N-90173-gfa0c9d69d3 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
  libavutil      56.  7.101 / 56.  7.101
  libavcodec     58. 13.100 / 58. 13.100
  libavformat    58. 10.100 / 58. 10.100
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 12.100 /  7. 12.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, matroska,webm, from 'De SprookjesBoom - S07E15 - De Grens.mkv':
  Metadata:
    encoder         : libmkv 0.6.5
  Duration: 00:05:00.52, start: 0.000000, bitrate: 1427 kb/s
    Stream #0:0(eng): Video: h264 (Main), yuv420p(tv, smpte170m/smpte170m/bt709, progressive), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 180k tbc (default)
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
Output #0, null, to 'NUL':
  Metadata:
    encoder         : Lavf58.10.100
    Stream #0:0(eng): Video: h264 (Main), yuv420p(tv, smpte170m/smpte170m/bt709, progressive), 720x576 [SAR 64:45 DAR 16:9], q=2-31, 25 fps, 25 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=    2 fps=0.0 q=-1.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=N/A
video:68kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

DEBUG: Found video stream at index 0
DEBUG: Found audio stream at index 1
INFO: Normalizing file De SprookjesBoom - S07E15 - De Grens.mkv (1 of 1)
DEBUG: Running normalization for De SprookjesBoom - S07E15 - De Grens.mkv
DEBUG: Parsing normalization info for De SprookjesBoom - S07E15 - De Grens.mkv
INFO: Running first pass loudnorm filter for stream 1
DEBUG: Running command: ['C:\\Windows\\system32\\ffmpeg', '-nostdin', '-y', '-i', 'De SprookjesBoom - S07E15 - De Grens.mkv', '-filter_complex', '[0:1]loudnorm=i=-24.0:lra=7.0:print_format=json:tp=-2.0:offset=0.0', '-vn', '-sn', '-f', 'null', 'NUL']
DEBUG: Loudnorm first pass command output:
DEBUG: ffmpeg version N-90173-gfa0c9d69d3 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
  libavutil      56.  7.101 / 56.  7.101
  libavcodec     58. 13.100 / 58. 13.100
  libavformat    58. 10.100 / 58. 10.100
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 12.100 /  7. 12.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, matroska,webm, from 'De SprookjesBoom - S07E15 - De Grens.mkv':
  Metadata:
    encoder         : libmkv 0.6.5
  Duration: 00:05:00.52, start: 0.000000, bitrate: 1427 kb/s
    Stream #0:0(eng): Video: h264 (Main), yuv420p(tv, smpte170m/smpte170m/bt709, progressive), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 180k tbc (default)
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:1 (aac) -> loudnorm
  loudnorm -> Stream #0:0 (pcm_s16le)
Output #0, null, to 'NUL':
  Metadata:
    encoder         : Lavf58.10.100
    Stream #0:0: Audio: pcm_s16le, 192000 Hz, stereo, s16, 6144 kb/s (default)
    Metadata:
      encoder         : Lavc58.13.100 pcm_s16le
size=N/A time=00:00:12.72 bitrate=N/A speed=24.7x
size=N/A time=00:00:26.22 bitrate=N/A speed=25.8x
size=N/A time=00:00:40.52 bitrate=N/A speed=26.5x
size=N/A time=00:00:54.12 bitrate=N/A speed=26.6x
size=N/A time=00:01:08.12 bitrate=N/A speed=26.9x
size=N/A time=00:01:22.72 bitrate=N/A speed=27.1x
size=N/A time=00:01:36.22 bitrate=N/A speed=  27x
size=N/A time=00:01:50.02 bitrate=N/A speed=27.1x
size=N/A time=00:02:03.82 bitrate=N/A speed=  27x
size=N/A time=00:02:17.12 bitrate=N/A speed=  27x
size=N/A time=00:02:30.22 bitrate=N/A speed=26.9x
size=N/A time=00:02:43.22 bitrate=N/A speed=26.9x
size=N/A time=00:02:56.42 bitrate=N/A speed=26.8x
size=N/A time=00:03:10.82 bitrate=N/A speed=26.9x
size=N/A time=00:03:25.22 bitrate=N/A speed=  27x
size=N/A time=00:03:39.52 bitrate=N/A speed=27.1x
size=N/A time=00:03:53.22 bitrate=N/A speed=27.1x
size=N/A time=00:04:07.42 bitrate=N/A speed=27.1x
size=N/A time=00:04:21.82 bitrate=N/A speed=27.2x
size=N/A time=00:04:36.12 bitrate=N/A speed=27.2x
size=N/A time=00:04:50.12 bitrate=N/A speed=27.3x
size=N/A time=00:04:58.02 bitrate=N/A speed=27.4x
video:0kB audio:223504kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Parsed_loudnorm_0 @ 0000022f8439ea00]
{
        "input_i" : "-35.44",
        "input_tp" : "-16.51",
        "input_lra" : "8.70",
        "input_thresh" : "-45.92",
        "output_i" : "-24.31",
        "output_tp" : "-4.61",
        "output_lra" : "6.40",
        "output_thresh" : "-34.71",
        "normalization_type" : "dynamic",
        "target_offset" : "0.31"
}

DEBUG: Loudnorm stats parsed: {"normalization_type": "dynamic", "input_tp": "-16.51", "output_thresh": "-34.71", "target_offset": "0.31", "output_i": "-24.31", "output_tp": "-4.61", "output_lra": "6.40", "input_lra": "8.70", "input_i": "-35.44", "input_thresh": "-45.92"}
INFO: Running second pass for De SprookjesBoom - S07E15 - De Grens.mkv
DEBUG: Running command: ['C:\\Windows\\system32\\ffmpeg', '-y', '-nostdin', '-i', 'De SprookjesBoom - S07E15 - De Grens.mkv', '-filter_complex', '[0:1]loudnorm=lra=7.0:linear=true:measured_thresh=-45.92:offset=0.0:i=-24.0:measured_i=-35.44:measured_tp=-16.51:measured_lra=8.7:tp=-2.0:print_format=json[norm1]', '-map_metadata', '0', '-map', '0:0', '-c:v', 'copy', '-map', '[norm1]', '-c:s', 'copy', '-c:a', 'ac3', '-b:a', '160k', 'c:\\users\\sa-dow~1\\appdata\\local\\temp\\2\\gm_six.mkv']
ERROR: Error while running command ['C:\\Windows\\system32\\ffmpeg', '-y', '-nostdin', '-i', 'De SprookjesBoom - S07E15 - De Grens.mkv', '-filter_complex', '[0:1]loudnorm=lra=7.0:linear=true:measured_thresh=-45.92:offset=0.0:i=-24.0:measured_i=-35.44:measured_tp=-16.51:measured_lra=8.7:tp=-2.0:print_format=json[norm1]', '-map_metadata', '0', '-map', '0:0', '-c:v', 'copy', '-map', '[norm1]', '-c:s', 'copy', '-c:a', 'ac3', '-b:a', '160k', 'c:\\users\\sa-dow~1\\appdata\\local\\temp\\2\\gm_six.mkv']!
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\ffmpeg-normalize.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\ffmpeg_normalize\__main__.py", line 327, in main
    ffmpeg_normalize.run_normalization()
  File "c:\python27\lib\site-packages\ffmpeg_normalize\_ffmpeg_normalize.py", line 158, in run_normalization
    media_file.run_normalization()
  File "c:\python27\lib\site-packages\ffmpeg_normalize\_media_file.py", line 116, in run_normalization
    self._second_pass()
  File "c:\python27\lib\site-packages\ffmpeg_normalize\_media_file.py", line 240, in _second_pass
    raise e
RuntimeError: Error running command ['C:\\Windows\\system32\\ffmpeg', '-y', '-nostdin', '-i', 'De SprookjesBoom - S07E15 - De Grens.mkv', '-filter_complex', '[0:1]loudnorm=lra=7.0:linear=true:measured_thresh=-45.92:offset=0.0:i=-24.0:measured_i=-35.44:measured_tp=-16.51:measured_lra=8.7:tp=-2.0:print_format=json[norm1]', '-map_metadata', '0', '-map', '0:0', '-c:v', 'copy', '-map', '[norm1]', '-c:s', 'copy', '-c:a', 'ac3', '-b:a', '160k', 'c:\\users\\sa-dow~1\\appdata\\local\\temp\\2\\gm_six.mkv']: ffmpeg version N-90173-gfa0c9d69d3 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
  libavutil      56.  7.101 / 56.  7.101
  libavcodec     58. 13.100 / 58. 13.100
  libavformat    58. 10.100 / 58. 10.100
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 12.100 /  7. 12.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, matroska,webm, from 'De SprookjesBoom - S07E15 - De Grens.mkv':
  Metadata:
    encoder         : libmkv 0.6.5
  Duration: 00:05:00.52, start: 0.000000, bitrate: 1427 kb/s
    Stream #0:0(eng): Video: h264 (Main), yuv420p(tv, smpte170m/smpte170m/bt709, progressive), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 180k tbc (default)
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:1 (aac) -> loudnorm
  Stream #0:0 -> #0:0 (copy)
  loudnorm -> Stream #0:1 (ac3)
[ac3 @ 00000258a47de580] invalid sample rate
Error initializing output stream 0:1 -- Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height
[Parsed_loudnorm_0 @ 00000258a47e0a80]
{
        "input_i" : "-inf",
        "input_tp" : "-inf",
        "input_lra" : "0.00",
        "input_thresh" : "-70.00",
        "output_i" : "-inf",
        "output_tp" : "-inf",
        "output_lra" : "0.00",
        "output_thresh" : "-70.00",
        "normalization_type" : "dynamic",
        "target_offset" : "inf"
}
Conversion failed!


C:\DATA\Private\temp\MakeMKV>
```

If I try the same thing on a different file it works
```

C:\DATA\Private\temp\MakeMKV>ffmpeg-normalize "De SprookjesBoom - S04E10 - De grootste gemenerik.mkv" -c:a ac3 -b:a 160k --debug
DEBUG: found executable in path: C:\Windows\system32\ffmpeg
DEBUG: found executable in path: C:\Windows\system32\ffmpeg
DEBUG: Running command: ['C:\\Windows\\system32\\ffmpeg', '-filters']
DEBUG: Parsing streams of De SprookjesBoom - S04E10 - De grootste gemenerik.mkv
DEBUG: Running command: ['C:\\Windows\\system32\\ffmpeg', '-i', 'De SprookjesBoom - S04E10 - De grootste gemenerik.mkv', '-c', 'copy', '-t', '0', '-map', '0', '-f', 'null', 'NUL']
DEBUG: Stream parsing command output:
DEBUG: ffmpeg version N-90173-gfa0c9d69d3 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
  libavutil      56.  7.101 / 56.  7.101
  libavcodec     58. 13.100 / 58. 13.100
  libavformat    58. 10.100 / 58. 10.100
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 12.100 /  7. 12.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, matroska,webm, from 'De SprookjesBoom - S04E10 - De grootste gemenerik.mkv':
  Metadata:
    encoder         : libmkv 0.6.5
  Duration: 00:05:00.36, start: 0.000000, bitrate: 931 kb/s
    Stream #0:0(eng): Video: h264 (Main), yuv420p(tv, smpte170m/smpte170m/bt709, progressive), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 180k tbc (default)
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
Output #0, null, to 'NUL':
  Metadata:
    encoder         : Lavf58.10.100
    Stream #0:0(eng): Video: h264 (Main), yuv420p(tv, smpte170m/smpte170m/bt709, progressive), 720x576 [SAR 64:45 DAR 16:9], q=2-31, 25 fps, 25 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=    2 fps=0.0 q=-1.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=N/A
video:58kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

DEBUG: Found video stream at index 0
DEBUG: Found audio stream at index 1
INFO: Normalizing file De SprookjesBoom - S04E10 - De grootste gemenerik.mkv (1 of 1)
DEBUG: Running normalization for De SprookjesBoom - S04E10 - De grootste gemenerik.mkv
DEBUG: Parsing normalization info for De SprookjesBoom - S04E10 - De grootste gemenerik.mkv
INFO: Running first pass loudnorm filter for stream 1
DEBUG: Running command: ['C:\\Windows\\system32\\ffmpeg', '-nostdin', '-y', '-i', 'De SprookjesBoom - S04E10 - De grootste gemenerik.mkv', '-filter_complex', '[0:1]loudnorm=i=-24.0:lra=7.0:print_format=json:tp=-2.0:offset=0.0', '-vn', '-sn', '-f', 'null', 'NUL']
DEBUG: Loudnorm first pass command output:
DEBUG: ffmpeg version N-90173-gfa0c9d69d3 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
  libavutil      56.  7.101 / 56.  7.101
  libavcodec     58. 13.100 / 58. 13.100
  libavformat    58. 10.100 / 58. 10.100
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 12.100 /  7. 12.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, matroska,webm, from 'De SprookjesBoom - S04E10 - De grootste gemenerik.mkv':
  Metadata:
    encoder         : libmkv 0.6.5
  Duration: 00:05:00.36, start: 0.000000, bitrate: 931 kb/s
    Stream #0:0(eng): Video: h264 (Main), yuv420p(tv, smpte170m/smpte170m/bt709, progressive), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 180k tbc (default)
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:1 (aac) -> loudnorm
  loudnorm -> Stream #0:0 (pcm_s16le)
Output #0, null, to 'NUL':
  Metadata:
    encoder         : Lavf58.10.100
    Stream #0:0: Audio: pcm_s16le, 192000 Hz, stereo, s16, 6144 kb/s (default)
    Metadata:
      encoder         : Lavc58.13.100 pcm_s16le
size=N/A time=00:00:12.62 bitrate=N/A speed=25.2x
size=N/A time=00:00:26.72 bitrate=N/A speed=26.3x
size=N/A time=00:00:40.92 bitrate=N/A speed=26.7x
size=N/A time=00:00:55.42 bitrate=N/A speed=27.1x
size=N/A time=00:01:09.92 bitrate=N/A speed=27.3x
size=N/A time=00:01:24.62 bitrate=N/A speed=27.5x
size=N/A time=00:01:39.22 bitrate=N/A speed=27.6x
size=N/A time=00:01:53.62 bitrate=N/A speed=27.7x
size=N/A time=00:02:07.72 bitrate=N/A speed=27.6x
size=N/A time=00:02:22.12 bitrate=N/A speed=27.6x
size=N/A time=00:02:36.52 bitrate=N/A speed=27.7x
size=N/A time=00:02:50.82 bitrate=N/A speed=27.7x
size=N/A time=00:03:05.12 bitrate=N/A speed=27.7x
size=N/A time=00:03:19.12 bitrate=N/A speed=27.6x
size=N/A time=00:03:33.42 bitrate=N/A speed=27.7x
size=N/A time=00:03:47.62 bitrate=N/A speed=27.6x
size=N/A time=00:04:01.62 bitrate=N/A speed=27.7x
size=N/A time=00:04:16.02 bitrate=N/A speed=27.7x
size=N/A time=00:04:30.22 bitrate=N/A speed=27.7x
size=N/A time=00:04:44.32 bitrate=N/A speed=27.7x
size=N/A time=00:05:01.43 bitrate=N/A speed=27.8x
size=N/A time=00:05:01.43 bitrate=N/A speed=27.8x
video:0kB audio:226064kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Parsed_loudnorm_0 @ 0000020569f616c0]
{
        "input_i" : "-17.97",
        "input_tp" : "-7.12",
        "input_lra" : "6.20",
        "input_thresh" : "-28.41",
        "output_i" : "-23.76",
        "output_tp" : "-10.14",
        "output_lra" : "5.40",
        "output_thresh" : "-34.13",
        "normalization_type" : "dynamic",
        "target_offset" : "-0.24"
}

DEBUG: Loudnorm stats parsed: {"normalization_type": "dynamic", "input_tp": "-7.12", "output_thresh": "-34.13", "target_offset": "-0.24", "output_i": "-23.76", "output_tp": "-10.14", "output_lra": "5.40", "input_lra": "6.20", "input_i": "-17.97", "input_thresh": "-28.41"}
INFO: Running second pass for De SprookjesBoom - S04E10 - De grootste gemenerik.mkv
DEBUG: Running command: ['C:\\Windows\\system32\\ffmpeg', '-y', '-nostdin', '-i', 'De SprookjesBoom - S04E10 - De grootste gemenerik.mkv', '-filter_complex', '[0:1]loudnorm=lra=7.0:linear=true:measured_thresh=-28.41:offset=0.0:i=-24.0:measured_i=-17.97:measured_tp=-7.12:measured_lra=6.2:tp=-2.0:print_format=json[norm1]', '-map_metadata', '0', '-map', '0:0', '-c:v', 'copy', '-map', '[norm1]', '-c:s', 'copy', '-c:a', 'ac3', '-b:a', '160k', 'c:\\users\\sa-dow~1\\appdata\\local\\temp\\2\\05hyht.mkv']
DEBUG: Normalization command output:
DEBUG: ffmpeg version N-90173-gfa0c9d69d3 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
  libavutil      56.  7.101 / 56.  7.101
  libavcodec     58. 13.100 / 58. 13.100
  libavformat    58. 10.100 / 58. 10.100
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 12.100 /  7. 12.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, matroska,webm, from 'De SprookjesBoom - S04E10 - De grootste gemenerik.mkv':
  Metadata:
    encoder         : libmkv 0.6.5
  Duration: 00:05:00.36, start: 0.000000, bitrate: 931 kb/s
    Stream #0:0(eng): Video: h264 (Main), yuv420p(tv, smpte170m/smpte170m/bt709, progressive), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 180k tbc (default)
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:1 (aac) -> loudnorm
  Stream #0:0 -> #0:0 (copy)
  loudnorm -> Stream #0:1 (ac3)
Output #0, matroska, to 'c:\users\sa-dow~1\appdata\local\temp\2\05hyht.mkv':
  Metadata:
    encoder         : Lavf58.10.100
    Stream #0:0(eng): Video: h264 (Main) (H264 / 0x34363248), yuv420p(tv, smpte170m/smpte170m/bt709, progressive), 720x576 [SAR 64:45 DAR 16:9], q=2-31, 25 fps, 25 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1: Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, stereo, fltp, 160 kb/s (default)
    Metadata:
      encoder         : Lavc58.13.100 ac3
frame= 1426 fps=0.0 q=-1.0 size=    9723kB time=00:00:57.10 bitrate=1394.9kbits/s speed= 111x
frame= 2975 fps=2885 q=-1.0 size=   14221kB time=00:01:59.05 bitrate= 978.5kbits/s speed= 115x
frame= 4461 fps=2884 q=-1.0 size=   19962kB time=00:02:58.57 bitrate= 915.7kbits/s speed= 115x
frame= 5881 fps=2852 q=-1.0 size=   25697kB time=00:03:55.34 bitrate= 894.5kbits/s speed= 114x
frame= 7388 fps=2866 q=-1.0 size=   33674kB time=00:04:55.56 bitrate= 933.3kbits/s speed= 115x
frame= 7507 fps=2877 q=-1.0 Lsize=   34042kB time=00:05:01.45 bitrate= 925.1kbits/s speed= 116x
video:28034kB audio:5888kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.353528%
[Parsed_loudnorm_0 @ 000002a1647f1bc0]
{
        "input_i" : "-17.94",
        "input_tp" : "-7.12",
        "input_lra" : "6.20",
        "input_thresh" : "-28.35",
        "output_i" : "-23.97",
        "output_tp" : "-13.15",
        "output_lra" : "6.20",
        "output_thresh" : "-34.38",
        "normalization_type" : "linear",
        "target_offset" : "-0.03"
}

DEBUG: Moving temporary file from c:\users\sa-dow~1\appdata\local\temp\2\05hyht.mkv to normalized\De SprookjesBoom - S04E10 - De grootste gemenerik.mkv
DEBUG: Normalization finished
INFO: Normalized file written to normalized\De SprookjesBoom - S04E10 - De grootste gemenerik.mkv

C:\DATA\Private\temp\MakeMKV>
```

**Comment by mdcollins05** [comment]
I had the same problem. Try adding '-ar 48000' to the command to fix it. That's what did it for me.

**Comment by Rouzax** [comment]
That did the trick :) thank you
