### ISSUE TITLE
normalize pcm raw audio

### ISSUE THREAD

**Issue by samanmohamadi** [slhck/ffmpeg-normalize#93]
ffmpeg-normalize does not detect input file format and I can't find any way to define it like ffmpeg(`-f s16le`)

**Command**
`ffmpeg-normalize /temp/6m-oDIKmqD.raw -o output.wav`

Any output you get when running the command with the `--debug` flag:

```
ERROR Traceback (most recent call last):
job-runner_1  |   File "/usr/local/bin/ffmpeg-normalize", line 11, in <module>
job-runner_1  |     sys.exit(main())
job-runner_1  |   File "/usr/local/lib/python3.6/dist-packages/ffmpeg_normalize/__main__.py", line 376, in main
job-runner_1  |     ffmpeg_normalize.add_media_file(input_file, output_file)
job-runner_1  |   File "/usr/local/lib/python3.6/dist-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 156, in add_media_file
job-runner_1  |     mf = MediaFile(self, input_file, output_file)
job-runner_1  |   File "/usr/local/lib/python3.6/dist-packages/ffmpeg_normalize/_media_file.py", line 41, in __init__
job-runner_1  |     self.parse_streams()
job-runner_1  |   File "/usr/local/lib/python3.6/dist-packages/ffmpeg_normalize/_media_file.py", line 64, in parse_streams
job-runner_1  |     cmd_runner.run_command()
job-runner_1  |   File "/usr/local/lib/python3.6/dist-packages/ffmpeg_normalize/_cmd_utils.py", line 115, in run_command
job-runner_1  |     raise RuntimeError("Error running command {}: {}".format(self.cmd, str(stderr)))
job-runner_1  | RuntimeError: Error running command ['/usr/bin/ffmpeg', '-i', '/temp/6m-oDIKmqD.raw', '-c', 'copy', '-t', '0', '-map', '0', '-f', 'null', '/dev/null']: ffmpeg version 4.1.1-0york1~18.04 Copyright (c) 2000-2019 the FFmpeg developers
job-runner_1  |   built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
job-runner_1  |   configuration: --prefix=/usr --extra-version='0york1~18.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-nonfree --enable-libfdk-aac --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
job-runner_1  |   libavutil      56. 22.100 / 56. 22.100
job-runner_1  |   libavcodec     58. 35.100 / 58. 35.100
job-runner_1  |   libavformat    58. 20.100 / 58. 20.100
job-runner_1  |   libavdevice    58.  5.100 / 58.  5.100
job-runner_1  |   libavfilter     7. 40.101 /  7. 40.101
job-runner_1  |   libavresample   4.  0.  0 /  4.  0.  0
job-runner_1  |   libswscale      5.  3.100 /  5.  3.100
job-runner_1  |   libswresample   3.  3.100 /  3.  3.100
job-runner_1  |   libpostproc    55.  3.100 / 55.  3.100
job-runner_1  | [image2 @ 0x55d5b383b500] Format image2 detected only with low score of 5, misdetection possible!
job-runner_1  | [rawvideo @ 0x55d5b383d5c0] Invalid pixel format.
job-runner_1  | [image2 @ 0x55d5b383b500] Failed to open codec in avformat_find_stream_info
job-runner_1  | [rawvideo @ 0x55d5b383d5c0] Invalid pixel format.
job-runner_1  |     Last message repeated 1 times
job-runner_1  | [image2 @ 0x55d5b383b500] Failed to open codec in avformat_find_stream_info
job-runner_1  | [image2 @ 0x55d5b383b500] Could not find codec parameters for stream 0 (Video: rawvideo, none): unspecified size
job-runner_1  | Consider increasing the value for the 'analyzeduration' and 'probesize' options
job-runner_1  | Input #0, image2, from '/temp/6m-oDIKmqD.raw':
job-runner_1  |   Duration: 00:00:00.04, start: 0.000000, bitrate: 934848 kb/s
job-runner_1  |     Stream #0:0: Video: rawvideo, none, 25 tbr, 25 tbn, 25 tbc
job-runner_1  | [null @ 0x55d5b3841b00] dimensions not set
job-runner_1  | Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
job-runner_1  | Stream mapping:
job-runner_1  |   Stream #0:0 -> #0:0 (copy)
job-runner_1  |     Last message repeated 1 times
job-runner_1  | 
job-runner_1  | 
job-runner_1  | Unhandled rejection (<Traceback (most recent call last):
job-runner_1  |   F...>, no stack trace)

```

**Environment (please complete the following information):**
- [ubuntu 18.04 ] Your operating system
- [2.7.15rc1] Your Python version / distribution (`python --version`)
- [ 4.1.1] Your ffmpeg version (`ffmpeg -version`)

**Comment by slhck** [comment]
This is by design. I'd recommend muxing the file first into something that can be read without extra input options. Having a format specifier like ffmpeg offers would be much too complicated (as it would have to support a lot of options).

**Comment by slhck** [comment]
Please mux raw audio to a container that can be read without further input information. For example:

    ffmpeg -f s16le -ar 44100 -ac 1 -i input.raw -c:a copy output.wav

Then continue to work with `output.wav`. As mentioned above, there may be more than one option necessary to specify input details, such as the sampling rate or number of channels. I unfortunately can't fully replicate ffmpeg's demuxer options in this script. (But PRs or suggestions how to implement it are welcome.)
