### ISSUE TITLE
Cannot normalize .avi file

### ISSUE THREAD

**Issue by lucasmr** [slhck/ffmpeg-normalize#94]
```
$ /home/user/.local/bin/./ffmpeg-normalize *.avi -c:a aac -b:a 192k

ERROR: Error while running command ['/usr/bin/ffmpeg', '-y', '-nostdin', '-i', 'video.avi', '-filter_complex', '[0:1]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=0.0:measured_i=-27.42:measured_lra=3.2:measured_tp=-7.62:measured_thresh=-37.46:linear=true:print_format=json[norm1]', '-map_metadata', '0', '-map_metadata:s:a:0', '0:s:a:0', '-map_metadata:s:v:0', '0:s:v:0', '-map_chapters', '0', '-map', '0:0', '-c:v', 'copy', '-map', '[norm1]', '-c:a', 'aac', '-b:a', '192k', '-c:s', 'copy', '/tmp/j_seghay.mkv']!
Traceback (most recent call last):
  File "/home/user/.local/bin/./ffmpeg-normalize", line 11, in <module>
    load_entry_point('ffmpeg-normalize==1.3.10', 'console_scripts', 'ffmpeg-normalize')()
  File "/home/user/.local/lib64/python3.6/site-packages/ffmpeg_normalize/__main__.py", line 378, in main
    ffmpeg_normalize.run_normalization()
  File "/home/user/.local/lib64/python3.6/site-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 174, in run_normalization
    media_file.run_normalization()
  File "/home/user/.local/lib64/python3.6/site-packages/ffmpeg_normalize/_media_file.py", line 132, in run_normalization
    for _ in self._second_pass():
  File "/home/user/.local/lib64/python3.6/site-packages/ffmpeg_normalize/_media_file.py", line 301, in _second_pass
    raise e
  File "/home/user/.local/lib64/python3.6/site-packages/ffmpeg_normalize/_media_file.py", line 287, in _second_pass
    for progress in cmd_runner.run_ffmpeg_command():
  File "/home/user/.local/lib64/python3.6/site-packages/ffmpeg_normalize/_cmd_utils.py", line 88, in run_ffmpeg_command
    raise RuntimeError("Error running command {}: {}".format(self.cmd, str("\n".join(stderr))))
RuntimeError: Error running command ['/usr/bin/ffmpeg', '-y', '-nostdin', '-i', 'video.avi', '-filter_complex', '[0:1]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=0.0:measured_i=-27.42:measured_lra=3.2:measured_tp=-7.62:measured_thresh=-37.46:linear=true:print_format=json[norm1]', '-map_metadata', '0', '-map_metadata:s:a:0', '0:s:a:0', '-map_metadata:s:v:0', '0:s:v:0', '-map_chapters', '0', '-map', '0:0', '-c:v', 'copy', '-map', '[norm1]', '-c:a', 'aac', '-b:a', '192k', '-c:s', 'copy', '/tmp/j_seghay.mkv']: ffmpeg version 3.4.5 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7.3.0 (Gentoo 7.3.0-r3 p1.4)
configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --docdir=/usr/share/doc/ffmpeg-3.4.5/html --mandir=/usr/share/man --enable-shared --cc=x86_64-pc-linux-gnu-gcc --cxx=x86_64-pc-linux-gnu-g++ --ar=x86_64-pc-linux-gnu-ar --optflags='-march=native -O2 -pipe' --disable-static --enable-avfilter --enable-avresample --disable-stripping --disable-libcelt --enable-nonfree --disable-indev=v4l2 --disable-outdev=v4l2 --disable-indev=oss --disable-indev=jack --disable-outdev=oss --enable-bzlib --disable-runtime-cpudetect --disable-debug --disable-gcrypt --disable-gnutls --disable-gmp --enable-gpl --enable-hardcoded-tables --enable-iconv --disable-lzma --enable-network --disable-opencl --enable-openssl --enable-postproc --disable-libsmbclient --enable-ffplay --enable-sdl2 --enable-vaapi --disable-vdpau --enable-xlib --enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-zlib --disable-libcdio --disable-libiec61883 --disable-libdc1394 --disable-libcaca --disable-openal --enable-opengl --disable-libv4l2 --enable-libpulse --disable-libdrm --disable-libopencore-amrwb --disable-libopencore-amrnb --disable-libfdk-aac --disable-libopenjpeg --disable-libbluray --disable-libgme --disable-libgsm --disable-mmal --disable-libmodplug --disable-libopus --disable-libilbc --disable-librtmp --disable-libssh --disable-libspeex --enable-librsvg --enable-libvorbis --disable-libvpx --disable-libzvbi --disable-appkit --disable-libbs2b --disable-chromaprint --disable-libflite --disable-frei0r --disable-libfribidi --disable-fontconfig --disable-ladspa --disable-libass --enable-libfreetype --disable-librubberband --disable-libzmq --disable-libzimg --disable-libsoxr --enable-pthreads --disable-libvo-amrwbenc --enable-libmp3lame --disable-libkvazaar --disable-nvenc --disable-libopenh264 --disable-libsnappy --disable-libtheora --disable-libtwolame --disable-libwavpack --disable-libwebp --enable-libx264 --disable-libx265 --enable-libxvid --disable-armv5te --disable-armv6 --disable-armv6t2 --disable-neon --disable-vfp --disable-vfpv3 --disable-armv8 --disable-mipsdsp --disable-mipsdspr2 --disable-mipsfpu --disable-altivec --disable-amd3dnow --disable-amd3dnowext --disable-avx2 --disable-fma3 --disable-fma4 --disable-xop --cpu=host --disable-doc --disable-htmlpages --enable-manpages
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100
Input #0, avi, from 'video.avi':
Metadata:
encoder         : FairUse Wizard - http://fairusewizard.com
Duration: 00:08:51.00, start: 0.000000, bitrate: 1373 kb/s
Stream #0:0: Video: h264 (Main) (H264 / 0x34363248), yuv420p(progressive), 640x464 [SAR 1:1 DAR 40:29], 1171 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc
Stream #0:1: Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, mono, fltp, 192 kb/s
Stream mapping:
Stream #0:1 (ac3) -> loudnorm
Stream #0:0 -> #0:0 (copy)
loudnorm -> Stream #0:1 (aac)
Output #0, matroska, to '/tmp/j_seghay.mkv':
Metadata:
encoder         : Lavf57.83.100
Stream #0:0: Video: h264 (Main) (H264 / 0x34363248), yuv420p(progressive), 640x464 [SAR 1:1 DAR 40:29], q=2-31, 1171 kb/s, 25 fps, 25 tbr, 1k tbn, 25 tbc
Stream #0:1: Audio: aac (LC) ([255][0][0][0] / 0x00FF), 48000 Hz, mono, fltp, 192 kb/s
Metadata:
encoder         : Lavc57.107.100 aac
[matroska @ 0x55e4b1b775c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 0x55e4b1b775c0] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
frame=    1 fps=0.0 q=-1.0 Lsize=      12kB time=00:00:00.57 bitrate= 172.8kbits/s speed=14.4x
video:1kB audio:11kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.902746%
[Parsed_loudnorm_0 @ 0x55e4b1ae7040]
{
"input_i" : "-inf",
"input_tp" : "-79.40",
"input_lra" : "0.00",
"input_thresh" : "-70.00",
"output_i" : "-inf",
"output_tp" : "-74.98",
"output_lra" : "0.00",
"output_thresh" : "-70.00",
"normalization_type" : "linear",
"target_offset" : "inf"
}
[aac @ 0x55e4b1b76580] Qavg: 49804.070
Conversion failed!

```

**Comment by slhck** [comment]
That seems like an upstream bug in ffmpeg to me, or a faulty input file which ffmpeg cannot handle (missing timestamps in the H.264 stream).

Does a normal

    ffmpeg -i input.avi -c:v copy -c:a aac output.mkv

work?

If not, does this work?

    ffmpeg -i input.avi -c:v copy -c:a aac -fflags +genpts output.mkv

What might also be worth trying is:

    ffmpeg -i input.avi -c copy input.mp4

Then continue working with the MP4 file.

**Comment by lucasmr** [comment]
Converting to mp4 first, then converting to mkv works just like you said. I wonder then, is this a limitation from upstream, and worth it to report?

**Comment by slhck** [comment]
There are several related tickets (at least from what I could find through a quick search):

- https://trac.ffmpeg.org/ticket/6903
- https://trac.ffmpeg.org/ticket/7411
- https://trac.ffmpeg.org/ticket/3339
- https://trac.ffmpeg.org/ticket/7434
